<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-container">
    <div class="footer">
        <div class="copy">
            <h5>your order</h5>
            <address>dopyright © 2018- 2019 dyKindofDress. </address>
        </div>
        <div class="service">
            <h5>customer service</h5>
            <p>customerservice@mykindofdress.com</p>
            <p>unit 1, fashion City, balymount, d24</p>

        </div>
        <div class="feature">
            <h5>features</h5>
            <div class="feature__col">
                <div class="feature__col__left">
                    <p>faqs</p>
                    <p>privacy policy</p>
                </div>
                <div class="feature__col__right">
                    <p>about us</p>
                    <p>delivery</p>
                </div>
            </div>
        </div>
    </div>
</div>
