<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="product-addto-links" data-role="add-to-links">
    <div class="fb"><i class="lab la-facebook-square"></i><span>Share</span></div>
    <div class="twitter"><i class="lab la-twitter"></i><span>Tweet</span></div>
    <div class="pin"><i class="lab la-pinterest"></i><span>Pin It</span></div>
</div>
