<div class="related-mkod">
    <h3>related products</h3>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('detail_list_product')->toHtml(); ?>
    
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".widget-new-grid").slick({
                dots: true,
                infinite: true,
                autoplay: true,
                speed: 300,
                autoplaySpeed: 20000000,
                slidesToShow: 5,
                slidesToScroll: 1,
                
                responsive: [
                    {
                        breakpoint: 1440,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 1074,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 992,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                ]
            });
        });
    });
</script>