<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter deskstop">
    <div class="filter-options" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
        <div data-role="collapsible" class="filter-options-item">
            <div data-role="title" class="filter-options-title"><span>Sort</span></div>
            <div data-role="content" class="filter-options-content">
                <select id="sorter" data-role="sorter" class="sorter-options" value-scope="">
                    <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                        <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                            <?php if ($block->isOrderCurrent($_key)) :?>
                                selected="selected"
                            <?php endif; ?>
                        >
                            <?= $block->escapeHtml(__($_order)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

    </div>
</div>
<div class="toolbar-sorter sorter mobile">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>
